### ISSUE TITLE
OLED only display logo then no display

### ISSUE THREAD

**Issue by lipk888** [kerisu/DivergenceMeter#1]
Hi Kerisu:
Many thank your great job for this nixie tube project.

so i have a issue for this software. when i succesful load program into the STM32F030 board, when progam running the OLED screen will show the logo, but just show logo then it will shut down and not have any dispaly. 
sorry my poor coding skill and i just do not have any change for code and just make HEX file and load into board.

can you help see if any my mistake? and i make video for issue, please for reference.

https://user-images.githubusercontent.com/59854686/103254755-9dce7080-49c1-11eb-9bd9-bdbdb857062a.MP4

**Comment by KX81** [comment]
Hi 
I'm not Kerisu(I'm KX81), you're wrong, but I'm also working on a divergence meter project, which is true so far I'm just at the initial stage

29 грудня 2020, 04:40:19, від "lipk888" < notifications@github.com >:



Hi Kerisu:
Many thank your great job for this nixie tube project.

so i have a issue for this software. when i succesful load program into the STM32F030 board, when progam running the OLED screen will show the logo, but just show logo then it will shut down and not have any dispaly.
sorry my poor coding skill and i just do not have any change for code and just make HEX file and load into board.

can you help see if any my mistake? and i make video for issue, please for reference.

https://user-images.githubusercontent.com/59854686/103254755-9dce7080-49c1-11eb-9bd9-bdbdb857062a.MP4

**Comment by lipk888** [comment]
ok, i just solve it, when flash the chips you need flash all chip, issue done many thanks

**Comment by kmakise** [comment]
Try&nbsp;it

**Comment by kmakise** [comment]
Options for Target -> Debug ->Settings(right) -> Flash Download -> Download function -> chose [Erase Full Chip]

**Comment by kerisu** [comment]
Options for Target -&gt; Debug -&gt;Settings(right) -&gt; Flash Download -&gt; Download function -&gt; chose [Erase Full Chip]
